-- =============================================================================
-- La tabla del CRUD de /solicitudes (solicitante/aprobador de vacaciones).
--
-- SQL estandar, no dialecto de PostgreSQL, mismo motivo que en el proyecto
-- original: que la migracion corra igual contra H2 (pruebas) y PostgreSQL.
-- =============================================================================

CREATE TABLE solicitud (
                           id                    BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           solicitante_email     VARCHAR(255)             NOT NULL,
                           fecha_inicio          DATE                     NOT NULL,
                           fecha_fin             DATE                     NOT NULL,
                           motivo                VARCHAR(500)             NOT NULL,
                           estado                VARCHAR(20)              NOT NULL,
                           comentario_aprobador  VARCHAR(500),
                           creado_en             TIMESTAMP WITH TIME ZONE NOT NULL,

                           CONSTRAINT estado_valido CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
                           CONSTRAINT fechas_coherentes CHECK (fecha_fin >= fecha_inicio)
);